### ISSUE TITLE
isBinaryFileSync + isBinaryFile

### ISSUE THREAD

**Issue by oncletom** [gjtorikian/isBinaryFile#11]
Reading the README, it is very strange to have `isBinaryFileSync` being async just because the second argument is a function.

Having the distinct functions would at least match Node.js sync/async declarations.

In any case, having a *Sync async function is just bad in term of naming.

**Comment by sindresorhus** [comment]
:+1: That is too magic.

What I usually do is export the async function on `module.exports` and then a sync function on `module.exports.sync`. Example: https://github.com/sindresorhus/read-chunk#api

**Comment by gjtorikian** [comment]
I'm going to implement a separate Sync method now, since there is interest.
