### ISSUE TITLE
package.json's "main" points to something nonexistent

### ISSUE THREAD

**Issue by wolfie** [gjtorikian/isBinaryFile#21]
the "main" points to `./lib/panino.js`. I think it should point to `./index.js` instead.

**Comment by gjtorikian** [comment]
Wow, what the hell? That's been like that since [the beginning](https://github.com/gjtorikian/isBinaryFile/commit/64981771d5d2aa49c3878c478b5446e079cf0db0)! Hah. Thanks.

**Comment by gjtorikian** [comment]
This PR fixed it: https://github.com/gjtorikian/isBinaryFile/pull/20

Shame on me for not keeping a closer eye on the project.
