### ISSUE TITLE
MAX_BYTES could be larger

### ISSUE THREAD

**Issue by alexjulien** [gjtorikian/isBinaryFile#28]
I have been using the Atom [open-plus](https://atom.io/packages/open-plus) package, which uses **isBinaryFile**. Some of the PDF documents I usually link to are correctly identified as binary files, but some other don't. Upon checking them, the first NUL character appears at around position 900, thus failing the MAX_BYTES=512 constraint. I've edited my local copy of isBinaryFile and upped the value to 1024 and this seems to do the trick.

Apparently, all the files I have issues with are PDF-1.3 generated with [CamScanner](http://www.camscanner.com).

**Comment by gjtorikian** [comment]
Would you mind adding one of the files to this issue so that I can check it out? You can drop PDF files right into the issue comment box: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by alexjulien** [comment]
[test.pdf](https://github.com/gjtorikian/isBinaryFile/files/590197/test.pdf)
Here is a sample, which happens to have its first NUL at 1090, rendering 1024 too low.

**Comment by gjtorikian** [comment]
Yup, precisely. I noticed [ag](https://github.com/ggreer/the_silver_searcher/blob/944e0111e29e399c92c8b30f8011213971fbffb3/src/util.c#L304) (which is where I stole this idea from) kept `MAX_BYTES` at 512 but checked for the PDF header. I should do that too. I'll get to this 🔜 .

**Comment by gjtorikian** [comment]
With the PDF file you gave me, the current test suite still passes and marks that file as binary: https://github.com/gjtorikian/isBinaryFile/pull/29

I have changed no logic to get the PDF to flag as binary. 

Are you saying the `open-plus` package does not mark it as binary? I wonder if they are doing something different?

**Comment by gjtorikian** [comment]
Taking my assignment off this. Waiting on feedback for the fact that the test passes.

**Comment by alexjulien** [comment]
I'm sorry I took so long to write back. I just recently could do the test with `isBinaryFile` isolated from the `open-plus` package, which passes just right. I even found that open-plus uses an older version of `isBinaryFile`. The problem seems to be elsewhere in `open-plus`.

Still, header-checking sounds like the kind of over-engineering I'd do ;)

Thanks for everything.

**Comment by gjtorikian** [comment]
Makes sense. I added that in d6f85fe270b9230bf5c0e3f8d38614a2b8c2f610.
