### ISSUE TITLE
Why does this exist?

### ISSUE THREAD

**Issue by balupton** [gjtorikian/isBinaryFile#35]
When https://www.npmjs.com/package/istextorbinary did it first

**Comment by gjtorikian** [comment]
Oh! I didn't realize that ideas had exclusivity to when a package was introduced.

One thing that's odd:

`istextorbinary`'s first commit? [Dec 2013](https://github.com/bevry/istextorbinary/commit/747ab2436f8effa3f632d3424f643790a86df07d)

This package? [Oct 2012](https://github.com/gjtorikian/isBinaryFile/commit/58a7fafb62fcd59a1d2b12aeb49a50e754144e7b)

![](https://i.gifer.com/Eks.gif)
