### ISSUE TITLE
Consider supporting Node v6?

### ISSUE THREAD

**Issue by fralonra** [gjtorikian/isBinaryFile#36]
`utils.promisify` is not supported by Node v6 or lower.

**Comment by gjtorikian** [comment]
I can promise (heh) to look into it, but Node v6 is [going to end-of-life](https://nodejs.org/en/about/releases/) in a few months, April 2019. I understand intimately that some projects may not be able to upgrade by then, but I think the pros of moving to a newer, secure, and supported Node outweigh the benefits of supporting the older platforms.

**Comment by fralonra** [comment]
I'm wondering what is the difference between `util.promisify(fs.somefunction)` and `fs.somefunctionSync`?

**Comment by fralonra** [comment]
See https://github.com/gjtorikian/isBinaryFile/releases/tag/v3.0.2
