### ISSUE TITLE
Please consistently use GitHub releases or add a CHANGELOG.md

### ISSUE THREAD

**Issue by Prinzhorn** [gjtorikian/isBinaryFile#41]
Thank you very much for providing this module. I'm asking you to please consistently use https://github.com/gjtorikian/isBinaryFile/releases or add a CHANGELOG.md. Or do both. Right now there is no way to easily tell what has changed betwen 4.0.0 and 4.0.6

**Comment by gjtorikian** [comment]
Your feedback is noted. You can use [the compare feature](https://github.com/gjtorikian/isBinaryFile/compare/4.0.0...master) to get a diff.

Typically if I don't do a proper release—and this is almost always true for patch releases—the changes are completely irrelevant to the program. I adhere strongly to [SemVer](https://semver.org/).

**Comment by Prinzhorn** [comment]
Thanks!
