### ISSUE TITLE
breaking changes to node engine included in patch release

### ISSUE THREAD

**Issue by zburke** [gjtorikian/isBinaryFile#51]
The lint changes introduced in 3c4f558a4c and published in [v4.0.9](https://github.com/gjtorikian/isBinaryFile/commit/99ba926c8446cbeeec8a2e9b7baa2cc11489e23c) changed the supported node runtime from `">= 8.0.0"` to `">= 14.0.0"`. This breaking change should have been released in a new major version instead.

**Comment by Pranavbhartia** [comment]
This is affecting our projects based on SAP Spartacus as well. We don't have control over the deployment environments and this change has now blocked us from deploying any changes to the SAP Commerce Cloud. 

Is there anything we can do to force a version, so yarn install doesn't pickup the latest version of the library? I couldn't find this library on the package.json, so not entirely sure how it's being referenced.

**Comment by brunohlippert** [comment]
Same problem here. As a temporary fix you can add this to your package.json file
`"resolutions": {
    "isbinaryfile": "4.0.8"
  },`

**Comment by Pranavbhartia** [comment]
> "resolutions": { "isbinaryfile": "4.0.8" },

Thank you so much for this @brunohlippert. Worked like a charm.

**Comment by zburke** [comment]
@Pranavbhartia , `isBinaryFile` is a dependency of [many, many things](https://www.npmjs.com/package/isbinaryfile). `yarn why isbinaryfile` (or `npm why isbinaryfile`) will show you your dependency tree so you can find out why it's being pulled into your project as a transitive dependency.

NB: `resolutions` is available in yarn only; in `npm` >= 8, use [`overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) to accomplish the same thing.

**Comment by gjtorikian** [comment]
The engine was changed because I don't want to encourage installations and support for old Node versions.

A solution as mentioned is to ping the version of the package; or, upgrade your Node version.

I'm quite surprised so many people are using this. Please consider sponsoring this project.

**Comment by mvilliger** [comment]
And how about publishing a fixed version 4.0.10 having the old node requirements and publish your new change as 5.0.0?
Then you could also drop the support for 4.0.10 and continue with 5.x?

**Comment by gjtorikian** [comment]
No thanks. Then people will ask me to support two releases. As features/security updates come into the 5.x branch, people will want them in the 4.x branch.

**Comment by mvilliger** [comment]
Yes, this might be possible. But still you could deny such requests. In my opinion this would still be better than introducing a breaking change.

**Comment by gjtorikian** [comment]
The request I am denying is to have two releases.

Pin to an older version, upgrade Node, fork this project, or sponsor me—those are the only choices.
