### ISSUE TITLE
Engines changes

### ISSUE THREAD

**Issue by crutchcorn** [gjtorikian/isBinaryFile#53]
In version 5.0.0, it seems like the `engines` field in `package.json` was set to `14`. I'm curious why this is done, because now I'm unable to update `node-plop` (where we're using it) to use this package. We want to support at least `12.20.0`, which also supports ESM. 

For reference, this is what our package.json looks like:

https://github.com/plopjs/plop/blob/master/packages/node-plop/package.json#L34

This engines property aligns fairly closely with many other ESM-supporting packages and I'm curious if there's any reason this project couldn't reflect something similar.

**Comment by gjtorikian** [comment]
Node 12 is EOL this week: https://nodejs.org/en/about/releases/

If the maintainers of the language won't support it, neither should a package.
