### ISSUE TITLE
Depricte warning for pod install /lib/panino.js'

### ISSUE THREAD

**Issue by maheshcode** [gjtorikian/isBinaryFile#57]
DeprecationWarning: Invalid 'main' field in '/opt/homebrew/lib/node_modules/pod/node_modules/isbinaryfile/package.json' of './lib/panino.js'

**Comment by gjtorikian** [comment]
Sounds like a problem with [pod](https://www.npmjs.com/package/pod) using an old version of this project; it was fixed [ages ago](https://github.com/gjtorikian/isBinaryFile/issues/21).
