### ISSUE TITLE
Node 18 is no longer supported in 5.0.1

### ISSUE THREAD

**Issue by strmer15** [gjtorikian/isBinaryFile#70]
While updating my PNPM lock file, I got the following message:

```
ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

This error happened while installing the dependencies of yeoman-test@8.2.0
 at mem-fs-editor@10.0.3

Your Node version is incompatible with "registry.npmjs.org/isbinaryfile/5.0.1".

Expected version: >= 20.0.0
Got: v18.19.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```

It looks like the 5.0.1 version [removed support for Node versions < 20](https://github.com/gjtorikian/isBinaryFile/commit/897a7557cb1427460d421e77343c35766556dda1) - while that's perfectly understandable for Node 16, Node 18 is [still supported until at least April 2025](https://nodejs.org/en/about/previous-releases).

Could you either restore support for Node 18 or else use a major version bump to remove support and keep the 5.x versions the way they used to be? Thanks for your support and maintenance of this package!

**Comment by gjtorikian** [comment]
Ah sure. I'll bump 6 to support >= 20, and put out 5.0.2 to lock back to >= 16. Sorry for the trouble.

**Comment by gjtorikian** [comment]
5.0.2 fixes this.

**Comment by strmer15** [comment]
Thanks so much for the quick response!
